SELECT * FROM RESTAURANT
NATURAL JOIN KOSHER_RESTAURANT NATURAL JOIN KOSHER_CERTIFICATE
WHERE CITY = &<name = "cityName" type = "string" default = "JERUSALEM"  >  AND K_LEVEL = 'MEADRIN'
ORDER BY R_ID

SELECT P_NAME, P_ID, END_DATE FROM
KOSHER_CERTIFICATE NATURAL JOIN KOSHER_PRODACT NATURAL JOIN PRODACT
WHERE CURRENT_DATE < END_DATE AND ADD_MONTHS(CURRENT_DATE , &<name = "numberOfMonth" type = "integer">) > END_DATE

UPDATE KOSHER_CERTIFICATE
SET END_DATE = TO_DATE( &NewEndDate, 'dd/mm/yyyy')
WHERE KC_ID IN (SELECT KC_ID FROM 
    KOSHER_RESTAURANT
    WHERE R_ID = &RESTURANT_ID)

UPDATE KOSHER_CERTIFICATE
SET K_LEVEL = &<name = NEWK_LEVEL list = "'mehadrin', 'badats', 'regular'">
WHERE KC_ID IN (SELECT KC_ID FROM 
    KOSHER_RESTAURANT
    WHERE R_ID = &RESTURANT_ID)